on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: true

    steps:
      - name: Checkout droolsjbpm-build-bootstrap
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/droolsjbpm-build-bootstrap
          repository: kiegroup/droolsjbpm-build-bootstrap
          fetch-depth: 0

      - name: Checkout kie-soup
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/kie-soup
          repository: kiegroup/kie-soup
          fetch-depth: 0

      - name: Checkout appformer
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/appformer
          repository: kiegroup/appformer
          fetch-depth: 0

      - name: Checkout kie-wb-common
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/kie-wb-common
          repository: kiegroup/kie-wb-common
          fetch-depth: 0

#      - name: Checkout drools-wb
#        uses: actions/checkout@v2
#        with:
#          path: ${{ github.workspace }}/drools-wb
#          repository: kiegroup/drools-wb
#          fetch-depth: 0

      - name: Checkout kogito-tooling
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/kogito-tooling
          repository: kiegroup/kogito-tooling
          fetch-depth: 0

      - name: Build droolsjbpm-build-bootstrap
        run: |
          mvn clean install -DskipTests -Dgwt.compiler.skip -Denforcer.skip -T 2 -B
          
      - name: Build kie-soup
        run: |
          mvn clean install -DskipTests -Dgwt.compiler.skip -Denforcer.skip -T 2 -B
          
      - name: Build appformer
        run: |
          mvn clean install -DskipTests -Dgwt.compiler.skip -Denforcer.skip -T 2 -B
          
      - name: Build kie-wb-common
        run: |
          mvn clean install -DskipTests -Denforcer.skip -T 2 -B -am -pl kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime,kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime
     
     - name: Build drools-wb
        run: |
          mvn clean install -DskipTests -Denforcer.skip -pl drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime -am -T 2 -B
          
      - name: Upload DMN editor
        uses: actions/upload-artifact@v1
        with:
          name: dmn-editor-fdb
          path: ${{ github.workspace }}/kie-wb-common/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/target/kie-wb-common-dmn-webapp-kogito-runtime

      - name: Upload BPMN editor
        uses: actions/upload-artifact@v1
        with:
          name: bpmn-editor-fdb
          path: ${{ github.workspace }}/kie-wb-common/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/target/kie-wb-common-stunner-bpmn-kogito-runtime

      - name: Publish BPMN editor
        env:
          EXTERNAL_RESOURCE_PATH__dmnEditor: "${{ github.workspace }}/kie-wb-common/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/target/kie-wb-common-dmn-webapp-kogito-runtime"
          EXTERNAL_RESOURCE_PATH__bpmnEditor: "${{ github.workspace }}/kie-wb-common/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/target/kie-wb-common-stunner-bpmn-kogito-runtime
        run: |
          xxxxxxxxx
        
